# Typos configuration
# https://github.com/crate-ci/typos

[files]
# Exclude external dependencies
extend-exclude = ["FxSsh/"]

[default.extend-identifiers]
# Windows API naming conventions use ordinals like 2nd, 3rd, 4th
FromLeft2ndButtonPressed = "FromLeft2ndButtonPressed"
FromLeft3rdButtonPressed = "FromLeft3rdButtonPressed"
FromLeft4thButtonPressed = "FromLeft4thButtonPressed"
# FxSsh library has a typo in their event name (external API, can't change)
ExceptionRasied = "ExceptionRasied"
OnExceptionRaised = "OnExceptionRaised"

[default.extend-words]
# Technical terms that are not typos
nd = "nd"
# Autocorrection example: intentional misspellings used as dictionary keys
impotr = "impotr"
improt = "improt"
wolrd = "wolrd"
wrold = "wrold"
teh = "teh"
hte = "hte"
# ANSI escape sequence "\x1b[4mis\x1b[0m" â€” typos sees "mis" but it's "is" after underline code
mis = "mis"
# Hex color codes (valid CSS colors, not typos)
daa = "daa"
ba = "ba"
# Auto-suggest test data: "ommit" is the suffix of "commit" when user types "git c"
ommit = "ommit"
# Test data: result of deleting a character from "hello"
helo = "helo"
# Test data: "helloworld" with cursor at position 5, ViAfter inserts X after 'w'
hellow = "hellow"
# Test data: "hello world" cut "lo wo" -> "hel" + "rld"
hel = "hel"
# Technical term: plural of IEnumerable (multiple enumerable objects)
enumerables = "enumerables"
# Vi command: "fo" means f (find char) + o (the character to find)
fo = "fo"
# Base64 encoded SSH keys contain random character sequences
Pn = "Pn"
# Lorem Ipsum text in full-screen examples (ported from Python Prompt Toolkit)
Nam = "Nam"
varius = "varius"
